using PdfGenAPI.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace PdfGenAPI.Components.Aims;

public class AimsOverallComponent(AimsModel data) : IComponent
{
    private readonly byte[] noCheck = File.ReadAllBytes(
        Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory,
            "img/checkbox-unchecked-svgrepo-com.png"
        )
    );

    private readonly byte[] yesCheck = File.ReadAllBytes(
        Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "img/checkbox-check-svgrepo-com.png")
    );

    private AimsModel _data = data;

    public void Compose(IContainer container)
    {
        uint rowCount = 0;
        container.Table(table =>
        {
            table.ColumnsDefinition(column =>
            {
                for (int i = 0; i < 36; i++)
                {
                    column.RelativeColumn();
                }
            });

            table.Cell().Row(++rowCount).Column(1).ColumnSpan(24).Text("Overall Severity").Bold();

            table
                .Cell()
                .Row(++rowCount)
                .Column(2)
                .ColumnSpan(24)
                .Text("8. Severity of abnormal movements");
            switch (_data.OverallSeverity)
            {
                case 0:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 1:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 2:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 3:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 4:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    break;
                default:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
            }

            table
                .Cell()
                .Row(++rowCount)
                .Column(2)
                .ColumnSpan(24)
                .Text("9. Incapacitation due to abnormal movements");
            switch (_data.OverallIncopacitation)
            {
                case 0:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 1:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 2:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 3:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 4:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    break;
                default:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
            }
            table
                .Cell()
                .Row(++rowCount)
                .Column(1)
                .ColumnSpan(36)
                .AlignCenter()
                .Padding(5)
                .Text(
                    "   0. No awareness - 1. Aware, no distress - 2. Aware, mild distress - 3. Aware, moderate distress - 4. Aware, severe distress   "
                )
                .BackgroundColor(Colors.Grey.Lighten4);
            table
                .Cell()
                .Row(++rowCount)
                .Column(2)
                .ColumnSpan(24)
                .Text("10. Patient's awareness of abnormal movements (rate only patient's report)");
            switch (_data.OverallAwareness)
            {
                case 0:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 1:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 2:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 3:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
                case 4:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(yesCheck);
                    break;
                default:
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(26)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(28)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(30)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(32)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    table
                        .Cell()
                        .Row(rowCount)
                        .Column(34)
                        .ColumnSpan(2)
                        .AlignCenter()
                        .Height(15)
                        .Image(noCheck);
                    break;
            }
        });
    }
}
