using GenPDF.Models;

namespace PdfGenAPI.Models;

public class PsychiatryEvalModel : BaseNoteModel
{
    public int SupcareFacId { get; set; }
    public string? IsPresent { get; set; }
    public string? AbsentNote { get; set; }
    public string? DxCode { get; set; }
    public string? DxCode2 { get; set; }
    public string? DxCode3 { get; set; }
    public string? DxCode4 { get; set; }
    public string? Allergies { get; set; }
    public string? Complaints { get; set; }
    public string? Source { get; set; }
    public string? CurrentIllness { get; set; }
    public bool? HxPsych { get; set; }
    public string? NpPsych { get; set; }
    public string? NpEndocrine { get; set; }
    public string? NpRespiratory { get; set; }
    public string? NpGu { get; set; }
    public string? NpNeuro { get; set; }
    public string? NpConstitutional { get; set; }
    public string? NpAmbulation { get; set; }
    public string? NpAdl { get; set; }
    public string? NpMusculoskeletal { get; set; }
    public string? NpCardio { get; set; }
    public string? NpSkin { get; set; }
    public string? NpGi { get; set; }
    public string? NpHematological { get; set; }
    public string? NpOther { get; set; }
    public string? NpOtherText { get; set; }
    public string? PhysicallExam { get; set; }
    public string? LabsOrderedOne { get; set; }
    public string? LabsOrderedTwo { get; set; }
    public string? LabsOrderedThree { get; set; }
    public string? LabsOrderedFour { get; set; }
    public string? LabsReviewedOne { get; set; }
    public DateTime? LabsReviewedOneDate { get; set; }
    public string? LabsReviewFindingsOne { get; set; }
    public string? LabsReviewOrderedOne { get; set; }
    public string? LabsReviewedTwo { get; set; }
    public DateTime? LabsReviewedTwoDate { get; set; }
    public string? LabsReviewFindingsTwo { get; set; }
    public string? LabsReviewOrderedTwo { get; set; }
    public string? LabsReviewedThree { get; set; }
    public DateTime? LabsReviewedThreeDate { get; set; }
    public string? LabsReviewFindingsThree { get; set; }
    public string? LabsReviewOrderedThree { get; set; }
    public string? LabsReviewedFour { get; set; }
    public DateTime? LabsReviewedFourDate { get; set; }
    public string? LabsReviewFindingsFour { get; set; }
    public string? LabsReviewOrderedFour { get; set; }
    public string? PhoneReview { get; set; }
    public string? PhoneWith { get; set; }
    public string? PhoneConversation { get; set; }
    public string? DocReview { get; set; }
    public string? DocFindings { get; set; }
    public string? MedicationOne { get; set; }
    public string? MedicationOneDosage { get; set; }
    public string? MedicationOneDosageChange { get; set; }
    public string? MedicationTwo { get; set; }
    public string? MedicationTwoDosage { get; set; }
    public string? MedicationTwoDosageChange { get; set; }
    public string? MedicationThree { get; set; }
    public string? MedicationThreeDosage { get; set; }
    public string? MedicationThreeDosageChange { get; set; }
    public string? MedicationFour { get; set; }
    public string? MedicationFourDosage { get; set; }
    public string? MedicationFourDosageChange { get; set; }
    public string? CondPrev { get; set; }
    public string? CondOne { get; set; }
    public string? CondOneStable { get; set; }
    public string? CondOneCourse { get; set; }
    public string? CondOnePlan { get; set; }
    public string? CondTwo { get; set; }
    public string? CondTwoStable { get; set; }
    public string? CondTwoCourse { get; set; }
    public string? CondTwoPlan { get; set; }
    public string? CondThree { get; set; }
    public string? CondThreeStable { get; set; }
    public string? CondThreeCourse { get; set; }
    public string? CondThreePlan { get; set; }
    public string? CondFour { get; set; }
    public string? CondFourStable { get; set; }
    public string? CondFourCourse { get; set; }
    public string? CondFourPlan { get; set; }
    public string? GDR { get; set; }
    public string? GdrText { get; set; }
    public string? NpAims { get; set; }
    public DateTime? AimsDate { get; set; }
    public string? Danger { get; set; }
    public string? ContSrvce { get; set; }
    public string? TeleHealth { get; set; }
    public string? NextScheduled { get; set; }
    public DateTime? EnterDate { get; set; }
    public string? EnterTime { get; set; }
    public DateTime? ModDate { get; set; }
    public string? ModTime { get; set; }
    public DateTime? SignatureDate { get; set; }
    public string? Covered { get; set; }
    public bool? TsDelete { get; set; }
    public string? Temp100 { get; set; }
    public string? Temp101 { get; set; }
    public string? Temp102 { get; set; }
    public string? Temp103 { get; set; }
    public string? Temp104 { get; set; }
    public string? Temp105 { get; set; }
    public string? Temp106 { get; set; }
    public string? Temp107 { get; set; }
    public string? Temp108 { get; set; }
    public string? Temp109 { get; set; }
    public string? Temp110 { get; set; }
    public string? Temp111 { get; set; }
    public string? Temp112 { get; set; }
    public string? Temp113 { get; set; }
    public string? Temp114 { get; set; }
    public string? Temp115 { get; set; }
    public string? Temp116 { get; set; }
    public string? Temp117 { get; set; }
    public string? Temp118 { get; set; }
    public string? Temp119 { get; set; }
    public string? Temp120 { get; set; }
    public string? Client { get; set; }
    public string? OrientImpair { get; set; }
    public string? DocRevName { get; set; }
    public string? Dx1Status { get; set; }
    public string? Dx1Severity { get; set; }
    public bool? Dx1Systemic { get; set; }
    public string? Dx1risk { get; set; }
    public string? Dx2Status { get; set; }
    public string? Dx2Severity { get; set; }
    public bool? Dx2Systemic { get; set; }
    public string? Dx2risk { get; set; }
    public string? Dx3Status { get; set; }
    public string? Dx3Severity { get; set; }
    public bool? Dx3Systemic { get; set; }
    public string? Dx3risk { get; set; }
    public string? Dx4Status { get; set; }
    public string? Dx4Severity { get; set; }
    public bool? Dx4Systemic { get; set; }
    public string? Dx4risk { get; set; }
    public bool? PhoneReviewDoc { get; set; }
    public string? PhoneWithDoc { get; set; }
    public string? PhoneConvDoc { get; set; }
    public string? Rational1 { get; set; }
    public string? Rational2 { get; set; }
    public string? Rational3 { get; set; }
    public string? Rational4 { get; set; }
    public bool? DocReviewDoc { get; set; }
    public string? DocRevNameDoc { get; set; }
    public string? DocRevFingingsDoc { get; set; }
    public int? SupacareCurrentFacId { get; set; }

    public List<HistoryModel>? HistoryList { get; set; }

    public int HistoryWordCount { get; set; }

    public string? AppCo { get; set; }
}
